camera:
  exposure_mode: auto
  iso: 100
  resolution:
  - 4056
  - 3040
  shutter_speed: 0
logging:
  csv_filename: timelapse_metadata.csv
  log_dir: logs
  log_level: INFO
timelapse:
  duration_hours: 24
  filename_prefix: timelapse
  interval_seconds: 30
  output_dir: output/images
